Repository fuchicorp/academy, pull requests merged in 2020-03, with the labels that each got.

#127 Fixed some bugs
  deployments/docker/app.py
Labels: enhancement

#130 Added back
  deployments/selenium/src/main/java/runners/CukesRunner.java
  deployments/selenium/src/main/java/utilities/Config.java
  deployments/selenium/src/main/java/utilities/DBUtility.java
  deployments/selenium/src/main/java/utilities/Driver.java
  deployments/selenium/src/main/java/utilities/SeleniumUtils.java
  deployments/selenium/src/main/java/utilities/TempStorage.java
  deployments/selenium/src/main/resources/features/academy.feature
  deployments/selenium/src/main/resources/features/singup.feature
Labels: QA

#133 Fixed index page
  deployments/docker/app.py
  deployments/docker/config.cfg
  deployments/docker/static/index/index.css
  deployments/docker/templates/index.html
Labels: enhancement

#135 implemented confirm password
  deployments/docker/app.py
  deployments/docker/requirements.txt
  deployments/docker/templates/signup.html
Labels: bug

#136 DEV -> QA password confirmation
  deployments/docker/app.py
  deployments/docker/requirements.txt
  deployments/docker/templates/signup.html
Labels: enhancement

#140 Fixed issue with login
  deployments/docker/app.py
Labels: bug

#141 Dev
  deployments/docker/app.py
Labels: bug

#142 Fixed issue with sign up and login
  deployments/docker/app.py
  deployments/docker/templates/user-permistions.html
Labels: bug

#143 Dev
  deployments/docker/app.py
  deployments/docker/templates/user-permistions.html
Labels: Features, enhancement

#145 Fixed issue with deploymnt
  deployments/docker/app.py
Labels: Features

#146 Dev
  deployments/docker/app.py
Labels: Features, enhancement

#147 Bugfix/138 to DEV
  deployments/docker/app.py
Labels: Features, bug, enhancement

#148 Dev
  deployments/docker/app.py
Labels: Features, enhancement

#149 Updated redirct
  deployments/docker/app.py
Labels: bug

#151 Dev
  deployments/docker/app.py
Labels: Features

#152 Deleted some packages from requirements
  deployments/docker/Dockerfile
  deployments/docker/bash/bin/get-kubectl.sh
  deployments/docker/requirements.txt
Labels: DEV features

#154 Dev
  deployments/docker/Dockerfile
  deployments/docker/app.py
  deployments/docker/bash/bin/get-kubectl.sh
  deployments/docker/requirements.txt
Labels: Features, enhancement

#159 Fixed issue 157 and ready to merge it
  deployments/docker/app.py
  deployments/docker/templates/chat.html
Labels: bug

#162 Dev
  deployments/docker/app.py
  deployments/docker/templates/chat.html
  deployments/docker/templates/dashboard.html
  deployments/docker/templates/profile.html
  deployments/docker/templates/settings.html
Labels: QA

#168 Fixed gitignore
  .gitignore
Labels: QA

#169 Fixed issue with default variables
  deployments/terraform/variables.tf
Labels: DEV Bug

#171 Fixed issue with chatting page
  .gitignore
  deployments/docker/templates/chat.html
Labels: DEV Bug

#173 Fixed issue with Pynote
  deployments/docker/app.py
Labels: DEV Bug

#175 Dev
  .gitignore
  deployments/docker/app.py
  deployments/docker/templates/chat.html
Labels: QA Features
