Repository fuchicorp/academy, pull requests merged in 2020-05, with the labels that each got.

#208 Kubernetes env`s moved to K8`s secret.
  deployments/terraform/academy.tf
  deployments/terraform/charts/academy/values.yaml
  deployments/terraform/secret.tf
Labels: DevOps Feature, Security

#212 Implemented pricing page
  deployments/docker/academy/common_statics/admin/css/base.css
  deployments/docker/academy/common_statics/admin/css/responsive.css
  deployments/docker/academy/common_statics/dashboard.css
  deployments/docker/academy/common_statics/footer.css
  deployments/docker/academy/common_statics/images/guy-man_BJVMVQEOP4.jpg
  deployments/docker/academy/common_statics/images/sp-sec-company-logo-sprite.webp
  deployments/docker/academy/common_statics/main/static.css
  deployments/docker/academy/common_templates/base.html
  deployments/docker/academy/common_templates/commin-soon.html
  deployments/docker/academy/common_templates/footer.html
  deployments/docker/academy/main/static/coming_soon.css
  deployments/docker/academy/main/static/dashboard/dashboard.css
  deployments/docker/academy/main/static/main/main-static.css
  deployments/docker/academy/main/static/settings/settings.css
  deployments/docker/academy/main/templates/main.html
  deployments/docker/academy/main/urls.py
  deployments/docker/academy/main/views.py
Labels: Dev Feature, Python

#213 Academy configured only organization members only
  deployments/docker/academy/common_templates/base.html
  deployments/docker/academy/settings.py
Labels: Dev Bug

#216 Fixed issue with showing all passwords with debug mode
  deployments/docker/Dockerfile
  deployments/docker/academy/settings.py
Labels: Dev Bug

#219 Created PayPal application and configuring deployment
  deployments/docker/academy/accounting/__init__.py
  deployments/docker/academy/accounting/admin.py
  deployments/docker/academy/accounting/apps.py
  deployments/docker/academy/accounting/migrations/__init__.py
  deployments/docker/academy/accounting/models.py
  deployments/docker/academy/accounting/static/accounting/accounting.css
  deployments/docker/academy/accounting/templates/paypal.html
  deployments/docker/academy/accounting/tests.py
  deployments/docker/academy/accounting/urls.py
  deployments/docker/academy/accounting/views.py
  deployments/docker/academy/common_templates/base.html
  deployments/docker/academy/common_templates/debug.html
  deployments/docker/academy/main/templates/debug.html
  deployments/docker/academy/main/templates/main.html
  deployments/docker/academy/settings.py
  deployments/docker/academy/urls.py
Labels: Dev Feature

#222 Hotfix/GitHub org
  deployments/docker/Dockerfile
  deployments/docker/academy/common_templates/base.html
  deployments/docker/academy/requirements.txt
  deployments/docker/academy/settings.py
Labels: Dev Bug

#227 Created docker compose and ready to use
  deployments/docker/Dockerfile
  deployments/docker/docker-compose.yaml
  deployments/terraform/charts/academy/templates/academy-deployment.yaml
Labels: Dev Feature, Django

#228 Created footer and ready to merge
  deployments/docker/academy/accounting/admin.py
  deployments/docker/academy/accounting/migrations/0001_initial.py
  deployments/docker/academy/accounting/models.py
  deployments/docker/academy/common_templates/footer.html
  deployments/docker/academy/init.py
  deployments/docker/academy/main/templates/main.html
  deployments/docker/academy/main/views.py
Labels: Dev Feature, Django

#233 signup page fixed and newsletter feature added
  .gitignore
  deployments/docker/academy/accounting/models.py
  deployments/docker/academy/accounting/templates/paypal.html
  deployments/docker/academy/accounting/urls.py
  deployments/docker/academy/accounting/views.py
  deployments/docker/academy/common_templates/base.html
  deployments/docker/academy/common_templates/footer.html
  deployments/docker/academy/main/forms.py
  deployments/docker/academy/main/models.py
  deployments/docker/academy/main/static/logo-img.png
  deployments/docker/academy/main/templates/main.html
  deployments/docker/academy/main/templates/newsletter/newsletter.html
  deployments/docker/academy/main/templates/signup.html
  deployments/docker/academy/main/urls.py
  deployments/docker/academy/main/views.py
  deployments/docker/academy/settings.py
  deployments/docker/academy/videos/views.py
Labels: Academy, Dev Feature

#240 Dev feature/paypall
  .gitignore
  deployments/docker/academy/accounting/migrations/0001_initial.py
  deployments/docker/academy/accounting/migrations/__init__.py
  deployments/docker/academy/accounting/templates/paypal.html
  deployments/docker/academy/accounting/urls.py
  deployments/docker/academy/accounting/views.py
  deployments/docker/academy/common_templates/footer.html
  deployments/docker/academy/common_templates/table.html
  deployments/docker/academy/common_templates/video.html
  deployments/docker/academy/info/migrations/__init__.py
  deployments/docker/academy/main/admin.py
  deployments/docker/academy/main/migrations/__init__.py
  deployments/docker/academy/main/models.py
  deployments/docker/academy/main/templates/main.html
  deployments/docker/academy/main/views.py
  deployments/docker/academy/videos/views.py
  deployments/docker/docker-compose.yaml
Labels: Academy, Dev Feature

#241 Created services and need's to work on deletion
  deployments/docker/academy/common_templates/base.html
  deployments/docker/academy/init.py
  deployments/docker/academy/kubernetes/pynote-ingress.yaml
  deployments/docker/academy/kubernetes/pynote-pod.yaml
  deployments/docker/academy/kubernetes/pynote-service.yaml
  deployments/docker/academy/requirements.txt
  deployments/docker/academy/services/__init__.py
  deployments/docker/academy/services/admin.py
  deployments/docker/academy/services/apps.py
  deployments/docker/academy/services/forms.py
  deployments/docker/academy/services/models.py
  deployments/docker/academy/services/static/style.css
  deployments/docker/academy/services/templates/services.html
  deployments/docker/academy/services/templates/user-service-delete.html
  deployments/docker/academy/services/templates/user-services.html
  deployments/docker/academy/services/tests.py
  deployments/docker/academy/services/urls.py
  deployments/docker/academy/services/views.py
  deployments/docker/academy/settings.py
  deployments/docker/academy/urls.py
  deployments/docker/academy/videos/views.py
  deployments/terraform/output.tf
Labels: Academy, Dev Feature

#242 hotfix docker
  .gitignore
  deployments/docker/Dockerfile
  deployments/docker/academy/settings.py
  deployments/docker/docker-compose.yaml
Labels: Dev Bug

#243 Dev feature/239
  deployments/docker/Dockerfile
  deployments/docker/academy/accounting/static/accounting/check.png
  deployments/docker/academy/accounting/static/accounting/declined.png
  deployments/docker/academy/accounting/templates/declined-payment.html
  deployments/docker/academy/accounting/templates/paypal.html
  deployments/docker/academy/accounting/templates/success-payment.html
  deployments/docker/academy/accounting/urls.py
  deployments/docker/academy/accounting/views.py
  deployments/docker/academy/main/templates/home.html
  deployments/docker/academy/main/views.py
Labels: Academy, Dev Feature
